// Code generated by MockGen. DO NOT EDIT.
// Source: ./cotizacionesRepository.go
//
// Generated by this command:
//
//	mockgen -source=./cotizacionesRepository.go -destination=./mock/cotizacionesRepository.go -package mock
//

// Package mock is a generated GoMock package.
package mock
